### ISSUE TITLE
Switch to commands

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-factory#1]
Currently this is tied to rom-sql as it uses `Relation#insert`, when we switch to commands it'll be possible to use it with any rom adapter.

⚠️  Let's target rom 4.0 as it'll provide a command generator ported from rom-repository ⚠️

**Comment by anicholson** [comment]
Got bit by this today, as I was trying to use `rom-yaml` for a new project as a quick way to get off the ground…
