### ISSUE TITLE
Question: what do you think about traits (like in FactoryGirl)?

### ISSUE THREAD

**Issue by cutalion** [rom-rb/rom-factory#10]
http://www.rubydoc.info/gems/factory_girl/file/GETTING_STARTED.md#Traits

```
factory :user, aliases: [:author]

factory :story do
  title "My awesome story"
  author

  trait :published do
    published true
  end

  trait :unpublished do
    published false
  end

  trait :week_long_publishing do
    start_at { 1.week.ago }
    end_at   { Time.now }
  end

  trait :month_long_publishing do
    start_at { 1.month.ago }
    end_at   { Time.now }
  end

  factory :week_long_published_story,    traits: [:published, :week_long_publishing]
  factory :month_long_published_story,   traits: [:published, :month_long_publishing]
  factory :week_long_unpublished_story,  traits: [:unpublished, :week_long_publishing]
  factory :month_long_unpublished_story, traits: [:unpublished, :month_long_publishing]
end
```

**Comment by cflipse** [comment]
I think I'm in favor of it

**Comment by solnic** [comment]
It's a matter of tweaking factory inheritance so that it supports more than one builder identifier, ie `Factory.define(user: [:active, :admin, :with_posts]) { |f| ... }`

**Comment by cflipse** [comment]
I think it'd be helpful / preferable if there's some way to include / specify a trait at usage time  ... so, you'd be able to do `Factory[:user, traits: [:admin, :with_posts]]` rather than needing to pre-define every combination you may end up using ...

**Comment by v-kolesnikov** [comment]
Would love to make PR. I personally really need this as well.
