### ISSUE TITLE
Support for all association types

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-factory#2]
Currently only `belongs_to` is supported

### TODO

- [x] `has_many`
- [x] `has_one`
- [x] `has_many-through`

**Comment by thiagopecanha** [comment]
Hey @solnic , May I handle this one?

**Comment by solnic** [comment]
@thiagopecanha I'm sorry but I missed your question :( Of course, feel free to work on it!

**Comment by thiagopecanha** [comment]
@solnic , ok

**Comment by solnic** [comment]
I *think* this is finished, but I need to make sure that we support everything here that rom itself supports.
