### ISSUE TITLE
Raise a nice exception when factory is not defined

### ISSUE THREAD

**Issue by solnic** [rom-rb/rom-factory#3]
Currently when you try to use a factory that was not defined you'll get an exception that doesn't tell you anything meaningful.

**Comment by GustavoCaso** [comment]
I will like to help with this one if there is no body working on this one

**Comment by solnic** [comment]
OK but let's wait until rom-4 branch is merged into master

**Comment by GustavoCaso** [comment]
no problem

**Comment by GustavoCaso** [comment]
It was fix by https://github.com/rom-rb/rom-factory/pull/15
