### ISSUE TITLE
0.7.0 release?

### ISSUE THREAD

**Issue by jswanner** [rom-rb/rom-factory#33]
Thanks for the great gem.

The CHANGELOG has been [made to look like the latest version should be 0.7.0](https://github.com/rom-rb/rom-factory/commit/fc6e668b452b5ba627abee10329eb7c5b5120752), but it doesn't look like a gem has been pushed nor is there a corresponding tag. Should the CHANGELOG be changed so that the 0.7.0 changes are marked as upcoming, or was 0.7.0 intended to have been released?

**Comment by solnic** [comment]
Sorry, I got distracted on that day and didn't manage to push 0.7.0, which I did just now https://rubygems.org/gems/rom-factory/versions/0.7.0
