### ISSUE TITLE
Error with `factories.structs[:relation]` after upgrade to 0.7.0

### ISSUE THREAD

**Issue by jswanner** [rom-rb/rom-factory#34]
In-memory struct creation that worked under 0.6.0 no longer works with 0.7.0

Factories defined as:

```ruby
factories.define(:account) do |f|
  f.email { fake(:internet, :email) }
  # ...
end

factories.define(:member) do |f|
  f.association(:account)
  f.name { fake(:name) }
  # ...
end
```

When I call `factories.structs[:member]`, I get the following error:

```
[ROM::Struct::Member.new] :account is missing in Hash input (Dry::Struct::Error)
```

I believe the problem is related to this line:

https://github.com/rom-rb/rom-factory/blob/94d29ea71292c6cff75177a5f990f3e7c37450ae/lib/rom/factory/tuple_evaluator.rb#L50

Before that method call, `attributes` does contain a value for the `:account` key, afterwards it does not.

**Comment by v-kolesnikov** [comment]
Hi @jswanner! Thank you for issue. We definitely should fix it in the next releases.
As a workaround you can move `association(:account)` to a trait.

**Comment by cutalion** [comment]
An example with pg_range attribute.

```
Factory.define(:announcement) do |f|
  f.when { Date.tomorrow.to_time.change(hour: 10)..Date.tomorrow.to_time.change(hour: 12) }
end

Factory[:announcement] # works
Factory.structs[:announcement] # doesn't work in 0.7.0

# Sequel::InvalidValue:
#       invalid or unhandled range format: "2018-12-06 10:00:00 +0300..2018-12-06 12:00:00 +0300"
```

**Comment by musaffa** [comment]
@cutalion It's a separate issue.

**Comment by solnic** [comment]
Can somebody provide a reproduction script? I didn't manage to reproduce this
