### ISSUE TITLE
Factory assumes my primary key is an integer sequence

### ISSUE THREAD

**Issue by backus** [rom-rb/rom-factory#4]
I have primary keys which are `bytea` strings. If I have a relation like this

```ruby
class Thing < ROM::Relation[:sql]
  schema(:things) do
    attribute :custom_id, ROM::SQL::Types::Blob
    attribute :name, String

    primary_key :custom_id
  end
end
```

and then my factory definition looks like this

```ruby
Factory = ROM::Factory.configure { |c| c.rom = rom }

Factory.define(:thing) do |f|
  f.sequence(:custom_id) { |_| File.binread('/dev/urandom', 10) }
  f.name 'some thing'
end
```

then the [factory builder will clobber it](https://github.com/rom-rb/rom-factory/blob/a1850901746a2eb13c26789a7183099bce3f6d0f/lib/rom/factory/builder.rb#L19).

It would be nice if it didn't. If I have a non-numeric primary key then I'd also love if it raised an error if I didn't define a sequence for it.

**Comment by solnic** [comment]
thanks for reporting this, unfortunately I won't have time to add support for this in the upcoming weeks, so a PR is welcome

**Comment by janjiss** [comment]
Started working on this, but will need an input.

If I create a table with a non-incremental string id
```
  conf.default.create_table(:table_name) do
    column :id, String, primary_key: true
  end
```
This line of code returns integer id: https://github.com/rom-rb/rom-factory/blob/master/lib/rom/factory/builder.rb#L61

I can circumvent that just by setting the value from tuple variable, but I wanted to know if there are any better solutions

**Comment by janjiss** [comment]
P.S This happens only with SQLite, since following line returns PK correctly:
https://github.com/rom-rb/rom-factory/blob/master/lib/rom/factory/builder.rb#L59

**Comment by solnic** [comment]
I'm working on rom-4.0 support in #6 and it'll fix this one (possibly already fixed but I need to add a spec to verify)
